name: Build and run docker image 
on: workflow_dispatch
jobs: 
 build_and_run: 
   runs_on: ubuntu-latest
   steps: 
    - name: checkout repository 
      uses: action/checkout@v4

    - name: Build Docker image 
      run: docker build -t my-app:latest 
